# Generated by Django 4.2 on 2024-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_category_blogs_author_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
